# Generated by Django 5.0.4 on 2024-05-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_ocupation_author_ocupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='second_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='second_title',
            field=models.CharField(blank=True, max_length=212, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='second_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='second_title',
            field=models.CharField(blank=True, max_length=212, null=True),
        ),
    ]
